# Always use double backslashes in Windows paths to avoid issues with escape characters.

pypsa_eur_test_case_path: 'C:\BeSt\VA-GA\PyPSA-Eur-all_v2026.02.0'
#pypsa_eur_test_case_path: "C:\\BeSt\\VA-GA\\WS-results"
results_path: "C:\\BeSt\\VA-GA\\results"
path_for_temporary_files: "C:\\BeSt\\VA-GA\\temp"

test_case: "base_s_all_elec_.nc"

preprocess_test_case: true
aggregate_stub_lines: false
temporal_aggregation: true
run_full_model_base: true

run_full_model_grid_expansion: 'false' # Options: true, false, 'presolved'
aggregate_geo_va: 'false' # Options: true, false, 'presolved'
aggregate_geo_non_va: 'false' # Options: true, false, 'presolved'
aggregate_elec_va: 'false' # Options: true, false, 'presolved
aggregate_elec_non_va: 'false' # Options: true, false, 'presolved'

solver_options: {
  LogToConsole: 0,
  ResultFile: 'infeasibility.ilp',
  Method: 2,  # -1, standard solving approach, 2 barrier only
  Crossover: 0,  # 0 no crossover
}

add_alternative_shortest_path_routes: false

optimization_options:
  include_line_expansion: true
  define_expandable_lines: 'predefined' # Options: 'all_congested_lines', 'all'

network_expansion_costs:
  line_expansion_cost_220: 12.37 # in Eur/MVA/km/a
  line_expansion_cost_380: 10.72 # in Eur/MVA/km/a
  trafo_expansion_cost_380-220: 136.78 # in Eur/MVA/a

geo_va_aggregation:
  num_of_clusters: 500
  strategy: 'va_geographical_kmedoids_haversine'  # Options: 'va_geographical', 'va_electrical_distance'

geo_non_va_aggregation:
  num_of_clusters: 500
  strategy: 'geographical_kmedoids_haversine'  # Options: 'geographical_kmeans', 'geographical_kmedoids_euclidean'

elec_va_aggregation:
  num_of_clusters: 500
  strategy: 'va_electrical_kmedoids'  # Options: 'va_geographical', 'va_electrical_kmedoids, va_electrical_hierarchical'

elec_non_va_aggregation:
  num_of_clusters: 500
  strategy: 'electrical_kmedoids'  # Options: 'va_geographical', 'va_electrical_kmedoids, va_electrical_hierarchical'

line_strategies:
  x: "equivalent_reactance"
  r: "equivalent_reactance"
  s_nom: "sum"
  length: "average"
  capital_cost: "average"
  s_max_pu: "average"
  num_parallel: "sum"
  s_nom_max: "sum"
  v_nom: "average"
  carrier: "first"

transformer_strategies:
  x: "equivalent_reactance"
  r: "equivalent_reactance"
  s_nom: "sum"
  capital_cost: "average"
  s_max_pu: "average"
  s_nom_max: "sum"
  carrier: "first"
  num_parallel: 'sum'
  tap_ratio: 'first'


temporal_clustering:
  clustering_strategy: 'downsampling'  # Options: 'downsampling', 'kmeans'
  n_timestep_clusters: 3

# Options for the native PyPSA aggregation strategy.
# We can specify clustering strategies for buses and lines.
# Using k-means on coordinates for buses is a geographical approach.
aggregation_options:
  bus_strategies:
    "1": "kmeans"
  line_strategies:
    "1": "length_capacity_weighted_average"
  generator_strategies:
    "1": "sum"
  storage_unit_strategies:
    "1": "sum"
