# Always use double backslashes in Windows paths to avoid issues with escape characters.

pypsa_eur_test_case_path: "C:\\BeSt\\VA-GA"
results_path: "C:\\BeSt\\VA-GA\\results"
path_for_temporary_files: "C:\\BeSt\\VA-GA\\temp"

test_case: "model_clustered_temporal_downsampling_3h.nc"

preprocess_test_case: false
aggregate_stub_lines: false
temporal_aggregation: false
run_full_model: false
aggregate_by_pypsa: false
aggregate_by_npap: true

solver_options: {
                  LogToConsole: 0,
                  ResultFile: 'infeasibility.ilp',
}

optimization_options:
  include_line_expansion: false

npap_aggregation:
  num_of_clusters: 200
  strategy: 'va_geographical_kmedoids_euclidean'  # Options: 'va_geographical', 'va_electrical_distance'

temporal_clustering:
  clustering_strategy: 'downsampling'  # Options: 'downsampling', 'kmeans'
  n_timestep_clusters: 3

# Options for the native PyPSA aggregation strategy.
# We can specify clustering strategies for buses and lines.
# Using k-means on coordinates for buses is a geographical approach.
aggregation_options:
  bus_strategies:
    "1": "kmeans"
  line_strategies:
    "1": "length_capacity_weighted_average"
  generator_strategies:
    "1": "sum"
  storage_unit_strategies:
    "1": "sum"

